# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

server:
  port: 9999
  contextPath: /springboot/v1
  # session最大超时时间(分钟)，默认为30
  session-timeout: 60
  tomcat:
    max-threads: 800
    uri-encoding: UTF-8
spring:
#    profiles:
#      active: dev
  application:
    name: springboot
  # ===================================================================
  # datasource config
  # ===================================================================
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springboot?useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 连接池初始化大小，最小，最大
    initial-size: 5
    min-idle: 5
    max-active: 20
    # 配置获取连接等待超时的时间
    max-wait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 300000
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    poolPreparedStatements: true
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j

debug: false

# ===================================================================
# JHipster specific properties
# ===================================================================
jhipster:
  security:
    jwt:
      #token 生成机制
      secret: 72808c83c09bb5d64de3061c7f93d2584ac0d37b
      # Token is valid 24 hours
      tokenValidityInSeconds: 86400

  swagger:
    title: rulegateway API
    description: rulegateway API documentation
    version: 0.0.1
    termsOfServiceUrl:
    contactName:
    contactUrl:
    contactEmail:
    license:
    licenseUrl:

# ===================================================================
# log config
# ===================================================================
logging:
  file: log/springboot.log
  config:
    classpath: logback-spring.xml
  level:
    org.springframework.web: DEBUG

